// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/Card.vue')['default']
    Cover: typeof import('./src/components/Cover.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScroll: typeof import('element-plus/es')['ElScroll']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElTag: typeof import('element-plus/es')['ElTag']
    Filter: typeof import('./src/components/Filter.vue')['default']
    Header: typeof import('./src/components/header.vue')['default']
    ICarbonPlay: typeof import('~icons/carbon/play')['default']
    ICarbonSearch: typeof import('~icons/carbon/search')['default']
    ICarbonUserAvatarFilled: typeof import('~icons/carbon/user-avatar-filled')['default']
    IIcRoundKeyboardArrowLeft: typeof import('~icons/ic/round-keyboard-arrow-left')['default']
    IIcRoundKeyboardArrowRight: typeof import('~icons/ic/round-keyboard-arrow-right')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    MusicHeader: typeof import('./src/components/MusicHeader.vue')['default']
    NetCarousel: typeof import('./src/components/NetCarousel.vue')['default']
    PicText: typeof import('./src/components/library/PicText.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    SongItem: typeof import('./src/components/SongItem.vue')['default']
    SongList: typeof import('./src/components/SongList.vue')['default']
    Test: typeof import('./src/components/Test.vue')['default']
  }
}

export {}
